### ISSUE TITLE
pop bug

### ISSUE THREAD

**Issue by mhrz** [vbonvin/ipt_connect#24]
![bug](https://cloud.githubusercontent.com/assets/11347262/22223612/f6d2ef0c-e1bb-11e6-8924-11290a1e86c1.png)

![rect3026](https://cloud.githubusercontent.com/assets/11347262/22223719/3f946f54-e1bc-11e6-9518-946d9373a7ea.png)

Bug when adding a new round without grade (to check for available problems)

**Comment by mhrz** [comment]
The problem is persistent, even with grades.

**Comment by xuod** [comment]
Solved by 61c24e527aa9bdc3e6add3426bd381bee494bf04

**Comment by mhrz** [comment]
Better! But there is now an error when no problem is selected (like a the beginning of a round, to check unavailable problems).

**Comment by xuod** [comment]
Now ?

**Comment by mhrz** [comment]
Seems all good! Good job :)
