### ISSUE TITLE
[IPT2017] Adapt FPT2017 to IPT2017

### ISSUE THREAD

**Issue by mhrz** [vbonvin/ipt_connect#28]
- Add the Final round

- Add the bonuspoints

- Modify the vetos and malus

- Modify the grades rejections

**Comment by xuod** [comment]
I just added the bonus points. Haven't tested it yet though.

**Comment by vbonvin** [comment]
Good. We'll make a test using the IPT2016 database

**Comment by mhrz** [comment]
Vivien, do you have time to check this this week-end? I guess this is the last opportunity to check it...

**Comment by vbonvin** [comment]
Yes, I'll have a look at it on Sunday. If @xuod could make sure the other points (penalties and grade rejections) are settled by then that would be neat, though.
