### ISSUE TITLE
Improve the ipt-connect interface

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/ipt_connect#32]
From @Vovcick:

Possible improvements:

Add the possibility to have two reporters
To add forbidden participants together with forbidden problems (not possible without 1)
To have created automatically rounds 2,3 (4) after creating the first one.
To improve fight stats in order to simplify control (just to have table of marks for all the rounds in a fight and bonuses together)
France 22.50 13.00 7.75 43.25 +1 44.25
Ukraine 24.00 12.50 8.25 44.75 +2 46.75
Bolivia 18.00 12.00 8.00 38.00 +0 38.00

**Comment by nickkolok** [comment]
This seems to be useful.

Possibly this should be split into separate issues :)

**Comment by vbonvin** [comment]
Indeed. I will do it a some point, but feel free to create a new issue and assign it to yourself if you want to work on a specific point right now :)

**Comment by nickkolok** [comment]
I've just splitted the issue into four issues referred above, so you can close it :-)

**Comment by vbonvin** [comment]
Thanks :)
