### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nickkolok** [vbonvin/ipt_connect#39]
Greetings from Russia!

Great respect for opening the source code! You've done certainly a brilliant work.

But to be fully able to use your system's forks to organize local tournaments and other tournaments, such as YIPT (city stages of which I helped to organise many times), we need a license provided by you.

I highly encourage you to use [GNU GPLv3](https://en.wikipedia.org/wiki/GNU_General_Public_License) in order to allow everyone to use your source code and in order to forbid anyone to build close-sourced systems basing on your code.

Stating the license will help to organise any kinds of tournaments worldwide and make the tournament movement more popular.

**Comment by vbonvin** [comment]
Hi nickkolok,

I'm glad to hear you are interested to use the software in the future! It's still a bit of a mess (hence the absence of license, documentation, etc...) but since there is interest in it I will put some resources on developing a stable and public version soon.

**Comment by nickkolok** [comment]
Hi @vbonvin, thank you in advance! We will wait for the license - which is crucial - and for initial documentation. Please feel free to share the drafts, maybe in separate branch :)
