### ISSUE TITLE
Problem sorting issue

### ISSUE THREAD

**Issue by nickkolok** [vbonvin/ipt_connect#41]
At page http://connect.iptnet.info/IPT2017/problems the problems are sorted by name, not by number, so the order is:
```
1. Handy glider
10. Light-driven vehicle
...
17. Magnetic fissioning of droplets
2. Too many magnets
```
And it probably should be different :)

As there will be license and documentation, I could try to fix it (it's just a Javascript issue), but I need guidelines on how to build the application and launch it.

**Comment by vbonvin** [comment]
Sorted on the dev branch by @ijustbsd , closing this issue
