### ISSUE TITLE
Empty database

### ISSUE THREAD

**Issue by ijustbsd** [vbonvin/ipt_connect#42]
Hi. I'm trying to run your program, but it works with IPT2018 only. When i open IPT2017 or IPT2016 i get error: `no such table: IPT201x_team`. Could you give me any database for testing or past years databases? I'll try to fix some issues and PR it.

**Comment by vbonvin** [comment]
Hi @ijustbsd,

I'm asking the executive commitee on the IPT to see if they agree to share the database with all the personal information from participants removed. If so, i'll put the database on github

**Comment by nickkolok** [comment]
@vbonvin, why don't you just replace, for example, Russia with Mordor, and participants' names with elf names from any generator?

**Comment by vbonvin** [comment]
That's what I've been doing, but still waiting for execom confirmation. Should be ok, though

**Comment by vbonvin** [comment]
You can find the anonymised db in the ipt_connect directory. Let me know if you have any issue using it.

@ijustbsd and @nickkolok, before you delve through the whole code, note that there has been a massive overhaul of the code between the IPT2016 and the following versions. The 2017 and 2018 versions are the same, except for a few hotfixes I quickly wrote last week.

I will open a dev branch on which you will be welcome to pull request any update or bugfix you'd care to write. It will be based on the IPT2017 code, which is the cleanest version of the app we have at the moment.

Closing this for now.
