### ISSUE TITLE
Test that filling FPT2017 does not affect IPT2016

### ISSUE THREAD

**Issue by vbonvin** [vbonvin/ipt_connect#6]
It may seems to be a boring test, but we want to be sure that the two tournaments do not overlap. They shouldn't but we better be sure.

Note that [playground.py]( https://github.com/vbonvin/ipt_connect/blob/master/ipt_connect/playground.py) can be used to fill rapidly the database with fake data.

**Comment by vbonvin** [comment]
Closing this, assuming @xuod did the tests before merging the branches.

**Comment by xuod** [comment]
Yep, everything seemed to work properly !
